name: DevOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Validate Ansible Playbook
        run: |
          cd ansible
          ansible-playbook playbook.yml --syntax-check
